NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Models/MessageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NoSql.PrimerEjemplo.Models
{
    public class MessageModel
    {

        public string from { get; set; }

        public string to { get; set; }

        public string message { get; set; }
    }
}

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Driver;
using NoSql.PrimerEjemplo.Collections;

namespace NoSql.PrimerEjemplo.Controllers
{
    public class AnimalController : Controller
    {
        static public MongoClient server = new MongoClient(ConfigurationManager.AppSettings.Get("mongoConnect"));
        static public IMongoDatabase db = server.GetDatabase(ConfigurationManager.AppSettings.Get("databaseName"));
        public AnimalController()
        {

            
            var animaes = db.GetCollection<Animales>("animales");
        }
        // GET: Animal
        public ActionResult Index()
        {
            
            return Json(db.Settings);
        }

        // GET: Animal/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Animal/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Animal/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Animal/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Animal/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Animal/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Animal/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Controllers/HomeController.cs
using NoSql.PrimerEjemplo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NoSql.PrimerEjemplo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult SayHello()
        {
            return View();
        }

        public ActionResult SayHelloToSomebody()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SayHelloToSomebody(MessageModel elmodelo)
        {

            return View("ShowMessageFromSomebody", elmodelo);
        }
    }
}

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Animal/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Animales!</h2>

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Home/SayHello.cshtml
@{
    ViewBag.Title = "SayHello";
}

<h2>SayHello</h2>
<p>Pruebas en MVC</p>

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Home/SayHelloToSomebody.cshtml
@model NoSql.PrimerEjemplo.Models.MessageModel

@{
    ViewBag.Title = "SayHelloToSomebody";
}

<h2>SayHelloToSomebody</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MessageModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.from, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.from, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.from, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.to, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.to, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.to, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Home/ShowMessageFromSomebody.cshtml
@model NoSql.PrimerEjemplo.Models.MessageModel

@{
    ViewBag.Title = "ShowMessageFromSomebody";
}

<h2>ShowMessageFromSomebody</h2>

<div>
    <h4>MessageModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.from)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.from)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.to)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.to)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NoSql.PrimerEjemplo/NoSql.PrimerEjemplo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Saludar", "SayHello", "Home")</li>
                    <li>@Html.ActionLink("Saludar a alguien", "SayHelloToSomebody", "Home")</li>
                    <li>@Html.ActionLink("Los animales", "Index", "Animal")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>